name = "penrose_tiling"
description= "Creates a SVG file with a Penrose tiling of the plane"
version = "1.0.0"
license    = "GPL-3.0-or-later"
author = "Vincent Magnin"
copyright = "Copyright 2023, vmagnin"
maintainer = "https://github.com/vmagnin/penrose_tiling/issues"
homepage   = "https://github.com/vmagnin/penrose_tiling"
categories = ["SVG", "graphics"]
keywords   = ["cairo-fortran", "Cairo", "Fortran", "fpm", "SVG", "aperiodic", "Penrose", "tiling"]

[dependencies]
cairo-fortran = {git = "https://github.com/vmagnin/cairo-fortran" }

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
